// Mock data for demo mode (when Supabase is not configured)
export const mockEmployees = [
  {
    id: '1',
    employee_id: 'EMP-001',
    full_name: 'Ahmed Hassan',
    email: 'ahmed@factory.com',
    username: 'ahmed',
    role: 'employee',
    department: 'Production',
    position: 'Machine Operator',
    phone: '+20 100 123 4567',
    hire_date: '2023-03-15',
    base_salary: 8500,
    shift: 'morning',
    insurance_start: '2023-04-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#6366f1',
  },
  {
    id: '2',
    employee_id: 'EMP-002',
    full_name: 'Fatma Ali',
    email: 'fatma@factory.com',
    username: 'fatma',
    role: 'employee',
    department: 'Administration',
    position: 'Admin Assistant',
    phone: '+20 101 234 5678',
    hire_date: '2022-08-01',
    base_salary: 7200,
    shift: 'morning',
    insurance_start: '2022-09-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#ec4899',
  },
  {
    id: '3',
    employee_id: 'EMP-003',
    full_name: 'Mohamed Saeed',
    email: 'mohamed@factory.com',
    username: 'mohamed',
    role: 'employee',
    department: 'Warehouse',
    position: 'Warehouse Supervisor',
    phone: '+20 102 345 6789',
    hire_date: '2021-11-20',
    base_salary: 9800,
    shift: 'evening',
    insurance_start: '2021-12-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#14b8a6',
  },
  {
    id: '4',
    employee_id: 'EMP-004',
    full_name: 'Sara Ibrahim',
    email: 'sara@factory.com',
    username: 'sara',
    role: 'employee',
    department: 'Packaging',
    position: 'Packaging Lead',
    phone: '+20 103 456 7890',
    hire_date: '2024-01-10',
    base_salary: 7000,
    shift: 'morning',
    insurance_start: '2024-02-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#f59e0b',
  },
  {
    id: '5',
    employee_id: 'EMP-005',
    full_name: 'Omar Khaled',
    email: 'omar@factory.com',
    username: 'omar',
    role: 'employee',
    department: 'Production',
    position: 'Quality Inspector',
    phone: '+20 104 567 8901',
    hire_date: '2023-06-05',
    base_salary: 8200,
    shift: 'night',
    insurance_start: '2023-07-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#8b5cf6',
  },
  {
    id: '6',
    employee_id: 'EMP-006',
    full_name: 'Nour Magdy',
    email: 'nour@factory.com',
    username: 'nour',
    role: 'employee',
    department: 'Warehouse',
    position: 'Inventory Clerk',
    phone: '+20 105 678 9012',
    hire_date: '2024-03-15',
    base_salary: 6500,
    shift: 'morning',
    insurance_start: '2024-04-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#06b6d4',
  },
  {
    id: '7',
    employee_id: 'EMP-007',
    full_name: 'Youssef Adel',
    email: 'youssef@factory.com',
    username: 'youssef',
    role: 'employee',
    department: 'Production',
    position: 'Line Supervisor',
    phone: '+20 106 789 0123',
    hire_date: '2022-02-28',
    base_salary: 10500,
    shift: 'evening',
    insurance_start: '2022-03-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#22c55e',
  },
  {
    id: '8',
    employee_id: 'EMP-008',
    full_name: 'Mona Tarek',
    email: 'mona@factory.com',
    username: 'mona',
    role: 'employee',
    department: 'Administration',
    position: 'HR Coordinator',
    phone: '+20 107 890 1234',
    hire_date: '2023-09-01',
    base_salary: 7800,
    shift: 'morning',
    insurance_start: '2023-10-01',
    insurance_active: true,
    status: 'active',
    avatar_color: '#e11d48',
  },
];

export const mockHRUser = {
  id: 'hr-1',
  employee_id: 'HR-001',
  full_name: 'Admin HR',
  email: 'hr@factory.com',
  username: 'hr',
  role: 'hr',
  department: 'Administration',
  position: 'HR Manager',
  phone: '+20 100 000 0000',
  hire_date: '2020-01-01',
  base_salary: 15000,
  shift: 'morning',
  insurance_start: '2020-01-01',
  insurance_active: true,
  status: 'active',
  avatar_color: '#6366f1',
};

const today = new Date();
const todayStr = today.toISOString().split('T')[0];
const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);
const twoDaysAgo = new Date(today); twoDaysAgo.setDate(today.getDate() - 2);

export const mockAttendance = [
  { id: '1', employee_id: '1', employee_name: 'Ahmed Hassan', department: 'Production', date: todayStr, check_in: `${todayStr}T06:05:00`, check_out: `${todayStr}T14:10:00`, shift: 'morning', delay_minutes: 5, working_hours: 8.08, status: 'present' },
  { id: '2', employee_id: '2', employee_name: 'Fatma Ali', department: 'Administration', date: todayStr, check_in: `${todayStr}T06:00:00`, check_out: `${todayStr}T14:00:00`, shift: 'morning', delay_minutes: 0, working_hours: 8, status: 'present' },
  { id: '3', employee_id: '3', employee_name: 'Mohamed Saeed', department: 'Warehouse', date: todayStr, check_in: `${todayStr}T14:12:00`, check_out: null, shift: 'evening', delay_minutes: 12, working_hours: 0, status: 'checked_in' },
  { id: '4', employee_id: '4', employee_name: 'Sara Ibrahim', department: 'Packaging', date: todayStr, check_in: null, check_out: null, shift: 'morning', delay_minutes: 0, working_hours: 0, status: 'absent' },
  { id: '5', employee_id: '5', employee_name: 'Omar Khaled', department: 'Production', date: todayStr, check_in: `${todayStr}T22:03:00`, check_out: null, shift: 'night', delay_minutes: 3, working_hours: 0, status: 'checked_in' },
  { id: '6', employee_id: '1', employee_name: 'Ahmed Hassan', department: 'Production', date: yesterday.toISOString().split('T')[0], check_in: `${yesterday.toISOString().split('T')[0]}T06:00:00`, check_out: `${yesterday.toISOString().split('T')[0]}T14:00:00`, shift: 'morning', delay_minutes: 0, working_hours: 8, status: 'present' },
  { id: '7', employee_id: '2', employee_name: 'Fatma Ali', department: 'Administration', date: yesterday.toISOString().split('T')[0], check_in: `${yesterday.toISOString().split('T')[0]}T06:15:00`, check_out: `${yesterday.toISOString().split('T')[0]}T14:05:00`, shift: 'morning', delay_minutes: 15, working_hours: 7.83, status: 'present' },
  { id: '8', employee_id: '3', employee_name: 'Mohamed Saeed', department: 'Warehouse', date: yesterday.toISOString().split('T')[0], check_in: `${yesterday.toISOString().split('T')[0]}T14:00:00`, check_out: `${yesterday.toISOString().split('T')[0]}T22:30:00`, shift: 'evening', delay_minutes: 0, working_hours: 8.5, status: 'present' },
];

export const mockLeaves = [
  { id: '1', employee_id: '1', employee_name: 'Ahmed Hassan', department: 'Production', type: 'Annual', start_date: '2026-04-20', end_date: '2026-04-24', days: 5, reason: 'Family vacation', status: 'pending', created_at: '2026-04-10T09:00:00' },
  { id: '2', employee_id: '2', employee_name: 'Fatma Ali', department: 'Administration', type: 'Sick', start_date: '2026-04-12', end_date: '2026-04-13', days: 2, reason: 'Medical appointment', status: 'approved', approved_by: 'Admin HR', created_at: '2026-04-11T08:30:00' },
  { id: '3', employee_id: '4', employee_name: 'Sara Ibrahim', department: 'Packaging', type: 'Emergency', start_date: '2026-04-15', end_date: '2026-04-15', days: 1, reason: 'Personal emergency', status: 'pending', created_at: '2026-04-14T17:00:00' },
  { id: '4', employee_id: '5', employee_name: 'Omar Khaled', department: 'Production', type: 'Annual', start_date: '2026-04-01', end_date: '2026-04-03', days: 3, reason: 'Travel', status: 'rejected', approved_by: 'Admin HR', created_at: '2026-03-28T10:00:00' },
  { id: '5', employee_id: '7', employee_name: 'Youssef Adel', department: 'Production', type: 'Annual', start_date: '2026-05-01', end_date: '2026-05-07', days: 7, reason: 'Annual holiday', status: 'pending', created_at: '2026-04-13T14:00:00' },
];

export const mockOvertime = [
  { id: '1', employee_id: '1', employee_name: 'Ahmed Hassan', department: 'Production', date: yesterday.toISOString().split('T')[0], hours: 2, reason: 'Production deadline', status: 'approved', rate: 1.5, approved_by: 'Admin HR' },
  { id: '2', employee_id: '3', employee_name: 'Mohamed Saeed', department: 'Warehouse', date: todayStr, hours: 1.5, reason: 'Inventory count', status: 'pending', rate: 1.5, approved_by: null },
  { id: '3', employee_id: '7', employee_name: 'Youssef Adel', department: 'Production', date: twoDaysAgo.toISOString().split('T')[0], hours: 3, reason: 'Machine maintenance', status: 'approved', rate: 2, approved_by: 'Admin HR' },
  { id: '4', employee_id: '5', employee_name: 'Omar Khaled', department: 'Production', date: todayStr, hours: 2, reason: 'Night shift coverage', status: 'pending', rate: 1.5, approved_by: null },
];

export const mockPayroll = [
  { id: '1', employee_id: '1', employee_name: 'Ahmed Hassan', department: 'Production', month: '2026-03', base_salary: 8500, overtime_pay: 580, bonuses: 500, performance_bonus: 300, penalties: 0, late_deductions: 50, absence_deductions: 0, net_salary: 9830, status: 'paid', paid_date: '2026-03-28' },
  { id: '2', employee_id: '2', employee_name: 'Fatma Ali', department: 'Administration', month: '2026-03', base_salary: 7200, overtime_pay: 0, bonuses: 200, performance_bonus: 250, penalties: 0, late_deductions: 150, absence_deductions: 0, net_salary: 7500, status: 'paid', paid_date: '2026-03-28' },
  { id: '3', employee_id: '3', employee_name: 'Mohamed Saeed', department: 'Warehouse', month: '2026-03', base_salary: 9800, overtime_pay: 420, bonuses: 0, performance_bonus: 400, penalties: 200, late_deductions: 0, absence_deductions: 0, net_salary: 10420, status: 'paid', paid_date: '2026-03-28' },
  { id: '4', employee_id: '4', employee_name: 'Sara Ibrahim', department: 'Packaging', month: '2026-04', base_salary: 7000, overtime_pay: 0, bonuses: 0, performance_bonus: 0, penalties: 0, late_deductions: 0, absence_deductions: 318, net_salary: 6682, status: 'processing', paid_date: null },
  { id: '5', employee_id: '5', employee_name: 'Omar Khaled', department: 'Production', month: '2026-04', base_salary: 8200, overtime_pay: 280, bonuses: 300, performance_bonus: 200, penalties: 0, late_deductions: 30, absence_deductions: 0, net_salary: 8950, status: 'processing', paid_date: null },
];

export const mockNotifications = [
  { id: '1', user_id: '1', type: 'leave_approved', title: 'Leave Request Approved', message: 'Your sick leave for Mar 5-6 has been approved.', read: false, created_at: '2026-04-14T10:00:00' },
  { id: '2', user_id: '1', type: 'salary_ready', title: 'Salary Available', message: 'Your March 2026 salary has been processed and is ready.', read: true, created_at: '2026-03-28T09:00:00' },
  { id: '3', user_id: 'hr-1', type: 'leave_request', title: 'New Leave Request', message: 'Ahmed Hassan has requested 5 days Annual leave.', read: false, created_at: '2026-04-10T09:00:00' },
  { id: '4', user_id: 'hr-1', type: 'leave_request', title: 'New Leave Request', message: 'Sara Ibrahim has requested 1 day Emergency leave.', read: false, created_at: '2026-04-14T17:00:00' },
  { id: '5', user_id: 'hr-1', type: 'action_required', title: 'Overtime Approval Required', message: 'Mohamed Saeed has logged 1.5 hours overtime pending approval.', read: false, created_at: '2026-04-15T08:00:00' },
];

export const mockAnnouncements = [
  { id: '1', title: 'Eid Al-Fitr Holiday', message: 'The factory will be closed from April 20-24 for Eid Al-Fitr. Wishing everyone a blessed holiday!', priority: 'high', created_by: 'Admin HR', department: 'All', created_at: '2026-04-13T08:00:00' },
  { id: '2', title: 'Safety Training - Mandatory', message: 'All Production and Warehouse employees must attend the safety training session on April 18th at 10:00 AM in the main hall.', priority: 'high', created_by: 'Admin HR', department: 'Production,Warehouse', created_at: '2026-04-12T09:00:00' },
  { id: '3', title: 'New Parking Regulations', message: 'Starting May 1st, all employees must display their vehicle pass in the windshield. Contact Administration for passes.', priority: 'medium', created_by: 'Admin HR', department: 'All', created_at: '2026-04-10T14:00:00' },
  { id: '4', title: 'Monthly Team Meeting', message: 'Monthly team meeting scheduled for April 25th. Department heads please prepare your reports.', priority: 'low', created_by: 'Admin HR', department: 'All', created_at: '2026-04-08T11:00:00' },
];

export const mockAuditLog = [
  { id: '1', action: 'LOGIN', user: 'Admin HR', details: 'HR user logged in', ip: '192.168.1.100', timestamp: '2026-04-15T08:00:00' },
  { id: '2', action: 'LEAVE_APPROVED', user: 'Admin HR', details: 'Approved sick leave for Fatma Ali (Apr 12-13)', ip: '192.168.1.100', timestamp: '2026-04-14T10:00:00' },
  { id: '3', action: 'OVERTIME_APPROVED', user: 'Admin HR', details: 'Approved 2h overtime for Ahmed Hassan', ip: '192.168.1.100', timestamp: '2026-04-14T09:30:00' },
  { id: '4', action: 'EMPLOYEE_UPDATED', user: 'Admin HR', details: 'Updated shift for Omar Khaled to Night', ip: '192.168.1.100', timestamp: '2026-04-13T16:00:00' },
  { id: '5', action: 'PAYROLL_PROCESSED', user: 'Admin HR', details: 'March 2026 payroll processed for 8 employees', ip: '192.168.1.100', timestamp: '2026-03-28T08:00:00' },
  { id: '6', action: 'ANNOUNCEMENT_CREATED', user: 'Admin HR', details: 'Created announcement: Eid Al-Fitr Holiday', ip: '192.168.1.100', timestamp: '2026-04-13T08:00:00' },
  { id: '7', action: 'LOGIN', user: 'Ahmed Hassan', details: 'Employee logged in', ip: '192.168.1.45', timestamp: '2026-04-15T06:00:00' },
  { id: '8', action: 'CHECK_IN', user: 'Ahmed Hassan', details: 'QR check-in at 06:05 AM (Production)', ip: '192.168.1.45', timestamp: '2026-04-15T06:05:00' },
  { id: '9', action: 'LEAVE_REQUESTED', user: 'Ahmed Hassan', details: 'Requested 5 days Annual leave (Apr 20-24)', ip: '192.168.1.45', timestamp: '2026-04-10T09:00:00' },
  { id: '10', action: 'CHECK_OUT', user: 'Ahmed Hassan', details: 'QR check-out at 02:10 PM (Production)', ip: '192.168.1.100', timestamp: '2026-04-15T14:10:00' },
];
